resume/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path("resume/", ResumeView.as_view(), name="resume"),
    path("resume/<username>", ResumeView.as_view(), name="resume"),
    path("resume/<username>/<language>", ResumeView.as_view(), name="resume"),
    path("pdf/<username>", ResumeAsPDF.as_view(), name="pdf"),
    path("pdf/<username>/<language>", ResumeAsPDF.as_view(), name="pdf"),
]

web_resume/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
import resume.urls as resume_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(resume_urls))
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/models.py
from django.db import models
from django.utils.translation import ugettext as _
from django.urls import reverse
from django.core.validators import RegexValidator


phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                             message="Phone number must be entered in the format: '+999999999'.")


class SocialMedia(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    base_url = models.URLField(_("Base URL"))
    icon_color = models.CharField(_("Color"), max_length=6)
    bi_icon = models.CharField(_("Icon"), max_length=100)

    class Meta:
        verbose_name = _("Social media")
        verbose_name_plural = _("Social medias")

    def __str__(self):
        return self.name

    def get_color(self):
        return "#%s" % self.icon_color


date_format = "b Y"


class SkillType(models.IntegerChoices):
    (SOFTWARE, PROGRAMING_LANGUAGE, PROGRAMING_TOOL, SOFTWARE_FRAMEWORK,
     ARCHITECTURE_PARADIGM, LANGUAGE, SOFT_SKILL) = enumerate(
        [
            _("Software"),
            _("Programing language"),
            _("Programing tool"),
            _("Software framework"),
            _("Architecture / Paradigm"),
            _("Language"),
            _("Soft skill"),
        ])


class Skill(models.Model):
    type = models.IntegerField(_("Skill type"),
                               choices=SkillType.choices,
                               blank=True,
                               null=True)

    name = models.CharField(_("Name"), max_length=100)

    class Meta:
        verbose_name = _("Skill")
        verbose_name_plural = _("Skills")
        ordering = ["type", "name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("skills", kwargs={"pk": self.pk})

user_profile/models.py
from uuid import uuid4

from django.db import models
from django.utils.translation import ugettext as _
from django.urls import reverse
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import date as date_filter

from resume.models import Skill, SocialMedia

date_format = "b Y"
phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                             message="Phone number must be entered in the format: '+999999999'.")


def profile_picture_file_path(user, filename: str):
    ext = filename.split('.')[-1]
    return f'profile_pictures/{uuid4()}.{ext}'


class UserProfile(AbstractUser):
    display_name = models.CharField(_("Display name"), max_length=100)
    title = models.CharField(_("Title"), max_length=100, blank=True)
    contact_email = models.EmailField(_("Contact email"),
                                      max_length=254,
                                      blank=True)
    contact_phone = models.CharField(
        validators=[phone_regex], max_length=17, blank=True)
    location = models.CharField(_("Location"), max_length=100, blank=True)
    website = models.URLField(_("Website"), max_length=256, blank=True)
    birthday = models.DateField(_("Birthday"), blank=True, null=True)

    picture = models.ImageField(_("Profile picture"),
                                upload_to=profile_picture_file_path,
                                blank=True)

    summary = models.TextField(_("Summary"), blank=True)

    skill_set = models.ManyToManyField("resume.Skill",
                                       verbose_name=_("skills"),
                                       through="user_profile.UserSkill",
                                       blank=True)
    socialmedia_set = models.ManyToManyField(
        "resume.SocialMedia",
        through="user_profile.UserSocialLink",
        verbose_name=_("Social media links"),
        blank=True)

    class Meta:
        verbose_name = _("user profile")
        verbose_name_plural = _("user profiles")

    def __str__(self):
        return f'{self.username}'

    def get_absolute_url(self):
        return reverse("profiles", kwargs={"pk": self.pk})

    def get_skills(self):
        return UserSkill.objects.filter(user=self).distinct()


class UserSocialLink(models.Model):
    """Model definition for UserSocialLink."""

    user = models.ForeignKey(UserProfile,
                             verbose_name=_("User profile"),
                             on_delete=models.CASCADE)
    socialmedia = models.ForeignKey(SocialMedia,
                                    verbose_name=_("Social media"),
                                    on_delete=models.CASCADE)
    username = models.CharField(_("Username or link"), max_length=100)
    link = models.URLField(_("Link"), max_length=200, blank=True)

    def get_link(self):
        if self.username in self.link and self.socialmedia.base_url in self.link:
            return self.link
        else:
            self.link = self.socialmedia.base_url + self.username
            self.save()
            return self.link

    class Meta:
        """Meta definition for SocialLink."""

        verbose_name = _("User's social media link")
        verbose_name_plural = _("User's social media links")

    def __str__(self):
        """Unicode representation of SocialLink."""
        return f'{self.username}@{self.socialmedia}'


class TimelineEvent(models.Model):
    user = models.ForeignKey(UserProfile,
                             verbose_name=_("User profile"),
                             on_delete=models.CASCADE)

    description = models.TextField(_("Description"))
    location = models.CharField(_("Location"), max_length=100)

    start_date = models.DateField(_("Start date"))
    end_date = models.DateField(_("End date"), blank=True, null=True)

    class Meta:
        abstract = True

    def period(self):
        if self.end_date:
            return _('from %(start_date)s to %(end_date)s') % {
                'start_date': date_filter(self.start_date, date_format),
                'end_date': date_filter(self.end_date, date_format)
            }
        else:
            return _('since %(start_date)s') % {
                'start_date': date_filter(self.start_date, date_format)
            }


class JobExperience(TimelineEvent):
    """Model definition for JobExperience."""

    company = models.CharField(_("Company"), max_length=100)
    role = models.CharField(_("Role"), max_length=100)
    skills_applied = models.ManyToManyField("user_profile.UserSkill",
                                            verbose_name=_("Skills applied"),
                                            blank=True)

    class Meta:
        """Meta definition for JobExperience."""

        verbose_name = _("Job experience")
        verbose_name_plural = _("Job experiences")
        ordering = ["-start_date"]

    def __str__(self):
        """Unicode representation of JobExperience."""
        return f'{self.role} at {self.company} ' + self.period()


class AcademicExperience(TimelineEvent):
    """Model definition for Academic experience."""

    school = models.CharField(_("School"), max_length=100)
    course = models.CharField(_("Course"), max_length=100)

    class Meta:
        """Meta definition for Education."""

        verbose_name = _("Academic experience")
        verbose_name_plural = _("Academic experiences")
        ordering = ["-start_date"]

    def __str__(self):
        """Unicode representation of Education."""
        return f'{self.course} at {self.school} ' + self.period()


class UserSkill(models.Model):
    user = models.ForeignKey(UserProfile,
                             verbose_name=_("User profile"),
                             on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill,
                              verbose_name=_("Skill"),
                              on_delete=models.CASCADE)
    level = models.IntegerField(
        _("Proficiency level"),
        choices=enumerate([
            _("Novice"),
            _("Beginner"),
            _("Competent"),
            _("Proficient"),
            _("Expert")
        ]),
        default=2,
    )

    class Meta:
        verbose_name = _("users' skill")
        verbose_name_plural = _("users' skills")

    def __str__(self):
        return self.skill.name

    def label(self):
        return _("%(p)s is %(l)s in %(s)s" % {'p': self.profile, 'l': self.get_level_display(), 's': self.skill})

    def get_absolute_url(self):
        return reverse("userskills", kwargs={"pk": self.pk})


def certificate_file_path(certificate, filename: str):
    ext = filename.split('.')[-1]
    return f'certificates/{certificate.user.username}/{uuid4()}.{ext}'


class Certificate(models.Model):
    user = models.ForeignKey(UserProfile,
                             verbose_name=_("User profile"),
                             on_delete=models.CASCADE)

    name = models.CharField(_("Name"), max_length=100)
    skill = models.ForeignKey(Skill,
                              verbose_name=_("Skill"),
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True)
    link = models.URLField(_("Certificate link"), max_length=200, blank=True)
    file = models.FileField(_("Certificate file"),
                            upload_to=certificate_file_path,
                            blank=True)

    duration = models.PositiveIntegerField(
        _("Duration in hours"), blank=True, null=True)

    class Meta:
        verbose_name = _("Certificate")
        verbose_name_plural = _("Certificates")

    def __str__(self):
        return self.name + (_(f" ({self.duration} hours)") if self.duration else "")

    def get_absolute_url(self):
        return reverse("certificates", kwargs={"pk": self.pk})


class PortfolioEntry(models.Model):
    user = models.ForeignKey(UserProfile,
                             verbose_name=_("User profile"),
                             on_delete=models.CASCADE)

    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(_("Description"), blank=True)
    cover = models.ImageField(_("Cover image"),
                              upload_to="portfolioentries",
                              blank=True)
    link = models.URLField(_("Link"), max_length=200, blank=True)
    date = models.DateField(_("Date"), blank=True, null=True)

    type = models.IntegerField(
        _("Entry type"),
        choices=enumerate([
            _("Side project"),
            _("Client project"),
            _("Product"),
            _("Publication"),
            _("POC")
        ]),
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = _("Portfolio")
        verbose_name_plural = _("portfolio entries")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("portfolioentries", kwargs={"pk": self.pk})

resume/views.py
from django.http.response import HttpResponse
from django.utils import translation
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.views.decorators.clickjacking import xframe_options_exempt
from django.utils.decorators import method_decorator

from user_profile.models import UserProfile
from web_resume import settings


@method_decorator(xframe_options_exempt, name='dispatch')
class ResumeView(TemplateView):
    template_name = "resume.html"

    def get_context_data(self,
                         username: str = None,
                         language: str = None,
                         *args,
                         **kwargs) -> HttpResponse:
        context = super().get_context_data(**kwargs)

        if username:
            profile: UserProfile = UserProfile.objects.get(username=username)
            # print(profile)
            context['profile'] = profile

        context['nopic'] = 'nopic' in self.request.GET

        if len(settings.LANGUAGES) > 1:
            context['languages'] = [{
                'name': lang[1],
                'url': f'{lang[0]}'
            } for lang in settings.LANGUAGES]

        if language:
            if translation.check_for_language(language):
                translation.activate(language)
            else:
                context['error'] = _(f'"{language}" is not a valid language code')

        return context

# from easy_pdf.views import PDFTemplateView

# class ResumeAsPDF(PDFTemplateView):
#     pass

from web_resume import renderers

class ResumeAsPDF(ResumeView):
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return renderers.render_to_pdf(self.template_name, context)

templates/resume.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load custom_tags %} {% load i18n %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <style>
      profile-picture {
        width: 150px;
      }
    </style>

    <title>{{ profile.display_name }}'s web resume</title>
  </head>

  <body id="page-top" class="bg-primary bg-opacity-50">
    <!-- Page content -->
    <div class="jumbotron m-5 mb-0">
      <!-- Post header -->
      <header class="d-flex justify-content-between mb-5">
        <!-- Post title -->
        <div class="hstack">
          <div>
            <h1 class="fw-bolder mb-1">{{ profile.display_name }}</h1>
            {% if profile.title %}
              <h3 class="mb-1">{{ profile.title }}</h3>
            {% endif %}
            {% if profile.location %}
              <h5><i class="bi bi-geo-alt"></i> {{ profile.location }}</h5>
            {% endif %}
            <br />
            <p>{{ profile.summary }}</p>
            <div>
              {% if profile.contact_email %}
                <a href="mailto:{{ profile.contact_email }}" class="btn btn-sm btn-outline-dark m-1"><i class="bi bi-envelope"></i> {{ profile.contact_email }}</a>
              {% endif %}

              {% if profile.contact_phone %}
                <a href="tel:{{ profile.contact_phone }}" class="btn btn-sm btn-outline-dark m-1"><i class="bi bi-telephone"></i> {{ profile.contact_phone }}</a>
              {% endif %}

              {% if profile.usersociallink_set.all %}
                {% for link in profile.usersociallink_set.all %}
                  <a href="{{ link.get_link }}" class="btn btn-sm btn-outline-dark m-1" title="{{ link.socialmedia.name }}"><i class="bi {{ link.socialmedia.bi_icon }}"></i> {{ link.username }}</a>
                {% endfor %}
              {% endif %}
            </div>
          </div>
        </div>

        <!-- Profile picture -->
        {% if profile.picture and not nopic %}
          <figure class="ms-5">
            <img class="rounded" style="width: 150px" src="{{ profile.picture.url }}" />
          </figure>
        {% endif %}
      </header>
    </div>
    <div class="container-fluid bg-white">
      <div class="row flex-wrap-reverse">
        <!-- Side widgets -->
        <div class="col-lg-3 mt-2">
          <!-- Contact information -->
          {% comment %}
          <div class="card mb-4">
            <div class="card-header">
              {% translate 'Contact information' %}
            </div>
            <div class="card-body d-flex flex-wrap">
              {% if profile.contact_email %}
                <a href="mailto:{{ profile.contact_email }}" class="btn btn-sm btn-outline-dark m-1">
                  <i class="bi bi-envelope"></i> {{ profile.contact_email }}
                  <!-- <br /> -->
                </a>
              {% endif %}
              <!--  -->

              {% if profile.contact_phone %}
                <a href="tel:{{ profile.contact_phone }}" class="btn btn-sm btn-outline-dark m-1">
                  <i class="bi bi-telephone"></i> {{ profile.contact_phone }}
                  <!-- <br /> -->
                </a>
                <!--  -->
              {% endif %}

              <!--       
          <a href="{{link.get_link}}" class="btn btn-outline-primary" style="border-radius: 50%" title="{{link.socialmedia.name}}">
         onmouseover="function a(){this.style.color={{link.socialmedia.get_color}}}"
               -->
              {% if profile.usersociallink_set.all %}
                {% for link in profile.usersociallink_set.all %}
                  <a href="{{ link.get_link }}" class="btn btn-sm btn-outline-dark m-1" title="{{ link.username }}"><i class="bi {{ link.socialmedia.bi_icon }}"></i> {{ link.socialmedia.name }}</a>
                  <!-- <br /> -->
                  <!--  -->
                {% endfor %}
              {% endif %}
            </div>
          </div>
          {% endcomment %}

          <!-- Skills -->
          {% comment %}
          {% if profile.get_skills.all %}
            <div class="card mb-4">
              <div class="card-header">
                {% get_verbose_name_plural profile.skill_set.first %}
              </div>
              <div class="card-body">
                <div>
                  {% for skill in profile.get_skills %}
                    <div class="badge rounded-pill bg-primary">{{ skill }}</div>
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endif %}
          {% endcomment %}

          <!-- Certificates -->
          {% if profile.certificate_set.all %}
            <div class="card mb-4">
              <!-- <div class="card-header">{% get_verbose_name_plural profile.certificate_set.first %}</div> -->
              <div class="card-header">
                {% translate 'Certificates' %}
              </div>
              <div class="card-body">
                <ul class="list-group list-group-flush">
                  {% for certificate in profile.certificate_set.all %}
                    <a href="{% if certificate.link %}
                        {{ certificate.link }}
                      {% elif certificate.file %}
                        {{ certificate.file.url }}
                      {% endif %}"
                      target="_blank"
                      class="list-group-item list-group-item-action">
                      {{ certificate }}
                    </a>
                  {% endfor %}
                </ul>
              </div>
            </div>
          {% endif %}
        </div>

        <div class="col-lg-8">
          <!-- Job experience -->
          {% if profile.jobexperience_set.all %}
            <section class="m-2 mb-4">
              <h2 class="fw-bolder">{% translate 'Job experiences' %}</h2>
              <!-- <h2 class="fw-bolder">{% get_verbose_name profile.jobexperience_set.first %}</h2> -->

              {% for job in profile.jobexperience_set.all %}
                <div class="card mb-2 bt-2">
                  <div class="card-header">
                    <div class="d-flex justify-content-between align-items-baseline">
                      <h4 class="card-title">{{ job.role }}</h4>
                      <small>{{ job.period }}</small>
                    </div>
                    <div class="d-flex text-muted justify-content-between align-items-baseline">
                      <h5>{{ job.company }}</h5>
                      <small class="ml-auto">{{ job.location }} <i class="bi bi-geo-alt"></i></small>
                    </div>
                  </div>
                  <div class="card-body">
                    <p class="card-text">{{ job.description }}</p>
                  </div>
                  <div class="card-footer">
                    <div>
                      {% for skill in job.skills_applied.all %}
                        <div class="badge rounded-pill bg-primary">{{ skill }}</div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              {% endfor %}
            </section>
          {% endif %}

          <!-- Academic experience -->
          {% if profile.academicexperience_set.all %}
            <section class="m-2 mb-4">
              <h2 class="fw-bolder mb-2">{% translate 'Academic experiences' %}</h2>

              {% for education in profile.academicexperience_set.all %}
                <div class="card mb-2 bt-2">
                  <div class="card-header">
                    <div class="d-flex justify-content-between align-items-baseline">
                      <h4 class="card-title">{{ education.course }}</h4>
                      <small>{{ education.period }}</small>
                    </div>
                    <div class="d-flex text-muted justify-content-between align-items-baseline">
                      <h5>{{ education.school }}</h5>
                      <small class="ml-auto">{{ education.location }} <i class="bi bi-geo-alt"></i></small>
                    </div>
                  </div>
                  <div class="card-body">
                    <p class="card-text">{{ education.description }}</p>
                  </div>
                </div>
              {% endfor %}
            </section>
          {% endif %}

          <!-- Portfolio -->
          {% if profile.portfolioentry_set.all %}
            <section class="m-2 mb-4">
              <h2 class="fw-bolder mb-2">{% get_verbose_name profile.portfolioentry_set.first %}</h2>

              <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
                {% for entry in profile.portfolioentry_set.all %}
                  <div class="col">
                    <div class="card m-2">
                      <!--        <div class=" card-header">
                        </div>        -->
                      <a href="{{ entry.link }}" style="color: inherit; text-decoration: inherit;">
                        <!--        <div class=" card-header">

                                </div>        -->
                        <div class="card-header justify-content-between align-items-baseline">
                          <h5 class="card-title">{{ entry.title }}</h5>

                          {% if entry.date %}
                            <small>{{ entry.date }}</small>
                          {% endif %}
                        </div>
                        <div class="card-body">
                          <p class="card-text">{{ entry.description }}</p>
                        </div>
                        <div class="card-footer"></div>
                      </a>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </section>
          {% endif %}
        </div>
      </div>
    </div>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Made by Caio Cantuária 2023</p>
        {% comment %}
        {% if languages %}
          <p>
            |{% for lang in languages %}
              <a href="{{ profile.username }}/{{ lang.url }}">{{ lang.name }}</a>
            {% endfor %}
          </p>
        {% endif %}
        {% endcomment %}
      </div>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <script src="https://kit.fontawesome.com/a076d05399.js " crossorigin="anonymous "></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js " integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj " crossorigin="anonymous "></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--       
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js " integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp " crossorigin="anonymous "></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js " integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/ " crossorigin="anonymous "></script>
       -->
  </body>
</html>